### ISSUE TITLE
AttributeError: aq_parent

### ISSUE THREAD

**Issue by reebalazs** [collective/collective.blog.portlets#4]
This may have been caused by the last hotfix, because I observed it just now and it was working before the fix.

When rendering the page on which there is a blog archives portlet, the exception below occurs. To be more exact... it breaks on my server but the same buildout and the same db does not break on my notebook, which I don't understand why.

I attempted to fix this on the ree-fix-aq-parent-error branch. However, handling acquisition issues is way over my level of competence, so while this simple fix worksforme, I am not sure if it's the correct solution. I would need someone to second it.

---

2013-06-20T09:46:40 ERROR Zope.SiteErrorLog 1371736000.470.895044140005 http://greenfinity.hu/en/blog/how-i-learned-to-stop-worrying-and-love-sublime-text/blogentry_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 60, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module Products.Five.browser.metaconfigure, line 476, in **call**
  Module Products.Five.browser.pagetemplatefile, line 125, in **call**
  Module Products.Five.browser.pagetemplatefile, line 59, in **call**
  Module zope.pagetemplate.pagetemplate, line 113, in pt_render
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
- URL: main_template
- Line 154, Column 16
- Expression: <StringExpr u'plone.rightcolumn'>
- Names:
    {'args': (),
     'container': <ATNewsItem at /Plone/en/blog/how-i-learned-to-stop-worrying-and-love-sublime-text>,
     'context': <ATNewsItem at /Plone/en/blog/how-i-learned-to-stop-worrying-and-love-sublime-text>,
     'default': <object object at 0xb75356b0>,
     'here': <ATNewsItem at /Plone/en/blog/how-i-learned-to-stop-worrying-and-love-sublime-text>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0xe2efcac>,
     'request': <HTTPRequest, URL=http://greenfinity.hu/en/blog/how-i-learned-to-stop-worrying-and-love-sublime-text/blogentry_view>,
     'root': <Application at >,
     'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0xe77560c>,
     'traverse_subpath': [],
     'user': <SpecialUser 'Anonymous User'>,
     'view': <Products.Five.metaclass.SimpleViewClass from /home/gfsite/sites/production1/eggs/Products.Scrawl-2.0b1-py2.7.egg/Products/Scrawl/browser/blogentry_view.pt object at 0xe4e7b8c>,
     'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0xe95874c>}
  Module zope.contentprovider.tales, line 77, in **call**
  Module plone.portlets.manager, line 75, in update
  Module collective.blog.portlets.archive, line 65, in update
  Module collective.blog.portlets.utils, line 20, in find_assignment_context
  AttributeError: aq_parent

**Comment by regebro** [comment]
I'll have time to look into this during the weekend.

**Comment by reebalazs** [comment]
Awesome, thanks!

**Comment by mauritsvanrees** [comment]
@erral has already fixed this on master, mostly in this commit: ea80fdfff5bb8b1993013d81a2b110beb203c672
He does the same as @reebalazs proposes, plus a bit more. Looks good to me and it works for me.

For impatient types, I have added a release of current master here:
http://pypi.zestsoftware.nl/public/collective.blog.portlets-1.5.zest.1.zip
If you add http://pypi.zestsoftware.nl/public/ (including the slash) to the find-links of your buildout and pin collective.blog.portlets to 1.5.zest.1, buildout should find it.

**Comment by erral** [comment]
Hi:

I don't know the exact implications of calling aq_base there (where @reebalazs calls), but it's OK for me.

**Comment by winnking** [comment]
I think there is still a problem. All is well on the main blog listing page but the contents of the Archive and Last Entries portlets do not show up on individual entries of the blog. The titles of the portlets show, but that's all.

Example from a PLone 2.2.5 site with collective.blog.star == 1.2 and collective.blog.portlets = 1.5.zest.1 :
http://www.ias-online.org/about-us/susan-trouts-blog/the-poison-leaves
As you can see, at the root of the blog, the entries DO appear in the portlets.

**Comment by regebro** [comment]
I hope you mean Plone 4.2.5. :-)

**Comment by winnking** [comment]
Yes Plone 4.2.5

**Comment by erral** [comment]
Aparently my fix doesn't work in some cases. I am running a Plone 4.3.2 with the master and the comparison is always false although the items are the same:
  if mapping[assignment_name]) is aq_base(assignment)

But if I compare this way, the comparison is True:

  if aq_base(mapping[assignment_name]) is aq_base(assignment)

Acquisition magic? I don't know...

**Comment by erral** [comment]
Ah sorry, this is what @reebalazs does on his branch. I'm going to merge it.
