### ISSUE TITLE
A bug or so.

### ISSUE THREAD

**Issue by dtordable** [collective/collective.blog.portlets#7]
I've seen a bug in blog.star. I have installed a product called collective.contentrules.yearmonth and I get created automatically the BLOG folders where to place the Pages and Images used by my BLOG.

The problem is that things like the Monthly archive appears absolutely empty. Also the tag cloud, but that's another project.

Let's see how do I solve that.

Thanks in advanced,
Daniel Tordable Dasilva

**Comment by regebro** [comment]
Released 1.6 that adds a portlet option for search depth.

**Comment by dtordable** [comment]
Thanks anyway.
